// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.coffeeco.protocol.coffee.common

object CoffeeCommonProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      com.coffeeco.protocol.coffee.common.CoffeeOrder
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChNjb2ZmZWUuY29tbW9uLnByb3RvIo0CCgtDb2ZmZWVPcmRlchIsCgl0aW1lc3RhbXAYASABKARCDuI/CxIJdGltZXN0YW1wU
  gl0aW1lc3RhbXASJwoIb3JkZXJfaWQYAiABKAlCDOI/CRIHb3JkZXJJZFIHb3JkZXJJZBInCghzdG9yZV9pZBgDIAEoCUIM4j8JE
  gdzdG9yZUlkUgdzdG9yZUlkEjAKC2N1c3RvbWVyX2lkGAQgASgJQg/iPwwSCmN1c3RvbWVySWRSCmN1c3RvbWVySWQSKgoJbnVtX
  2l0ZW1zGAUgASgNQg3iPwoSCG51bUl0ZW1zUghudW1JdGVtcxIgCgVwcmljZRgGIAEoAkIK4j8HEgVwcmljZVIFcHJpY2VCHwoVY
  29tLmNvZmZlZWNvLnByb3RvY29sQgZDb21tb25iBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}